services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: marlontest
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432" # 5332 -> request coming from localhost will be redirected to 5432 -> actual docker instance running on docker
    networks:
      - db
    restart: unless-stopped


networks:
  db:
    driver: bridge

volumes:
  db: