services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: marlontest
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customer
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
#    env_file:
#      - .env
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
  pgadmin: