server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: marlontest
    password: password
  jpa:
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: validate # validates if the Customer entity matches with the schema with Flyway
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

#networks:
#  default:
#    external:
#      name: postgres